general {
  after_sleep_cmd=hyprctl dispatch dpms on
  before_sleep_cmd=hyprlock
  lock_cmd=pgrep hyprlock || hyprlock
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -s set 10
  timeout=150
}

listener {
  on-timeout=hyprlock
  timeout=300
}

listener {
  on-resume=hyprctl dispatch dpms on
  on-timeout=hyprctl dispatch dpms off
  timeout=330
}

listener {
  on-timeout=systemctl suspend || loginctl suspend
  timeout=1800
}

