# windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
# windowrule = match:class .*, suppressevent maximize 

#---------------Window Rules

#----------Kitty
windowrule = match:class kitty, opacity 0.75

#----------File Picker
windowrule = match:title ^(Open Folder)$, float on
windowrule = match:title ^(Open Folder)$, size 700 500

#----------Obsidian
windowrule = match:class ^(obsidian)$, opacity 0.97

#----------Blueman
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, size 500 700

#----------Zathura
windowrule = match:class ^(Zathura)$, opacity 0.75

#----------Zotero
windowrule = match:class ^(Zotero)$, opacity 0.85

#----------Emacs
windowrule = match:class ^(Emacs)$, opacity 0.90

#----------Calculator
windowrule = match:title ^(Calculator)$, float on

#----------File Manager
windowrule = match:class ^(org.gnome.Nautilus)$, float on

#---------------Layer Rules

#----------Rofi
layerrule = blur on, match:namespace rofi

#----------Swaync
layerrule = animation slide right, match:namespace swaync-control-center

