background {
  blur_passes = 3
  blur_size = 8
  path = ~/.current_wallpaper
}

general {
  disable_loading_bar = true
  grace = 300
  hide_cursor = true
  no_fade_in = false
}

input-field {
  size = 200, 50
}

