# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

# INFO: having issues. adding some of my old configs in order to test

# #---------------tells dbus about the current desktop
# debug:disable_logs = false
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
# openrc will ignore systemd flag. command will still work
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

#---------------kills all existing desktop portals; starts hyprlands
exec-once = ~/.config/hypr/xdg-portal-hyprland

#---------------starts polkit agent
exec-once = /usr/libexec/hyprpolkitagent

#---------------starts pipewire
exec-once = /usr/bin/gentoo-pipewire-launcher restart &

# END



$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Defaults
source=hyprland/env.conf
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=hyprland/keybinds.conf

# Custom 
source=custom/env.conf
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf