# $lock_cmd = swaylock -c 000000
$lock_cmd = pgrep hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    # after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

listener {
    timeout = 150 # 2.5 minutes
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
}

# BUG: Having problems with intel devices and suspending. Doesn't seem fixable

# listener {
#     timeout = 600 # 10mins
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on && brightnessctl -r
# }
#
# listener {
#     timeout = 1800 # 30mins
#     on-timeout = $suspend_cmd
# }