server:
    interface: 127.0.0.1
    port: 53
    do-ip4: yes
    do-ip6: no
    do-tcp: yes
    access-control: 127.0.0.0/8 allow

    verbosity: 1
    log-queries: yes

    cache-min-ttl: 3600
    cache-max-ttl: 86400

    pidfile: /var/run/unbound.pid
    username: unbound

    auto-trust-anchor-file: /etc/unbound/dnssec-trust-anchors.key

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853    # cloudflare
    forward-addr: 9.9.9.9@853    # quad9
    forward-addr: 8.8.8.8@853    # google
