# locations
database=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new
report_url=file:/var/log/aide/aide.log

# rules

Checksums = sha512+sha256+rmd160+tiger

NORMAL = p+i+n+u+g+s+m+c+Checksums
LOGS   = p+u+g+n+S
CONF   = p+i+n+u+g+s+m+c+Checksums
BINLIB = p+i+n+u+g+s+m+c+Checksums

# directories

/bin            BINLIB
/sbin           BINLIB
/usr/bin        BINLIB
/usr/sbin       BINLIB
/lib            BINLIB
/lib64          BINLIB
/usr/local/bin  BINLIB
/usr/local/sbin BINLIB

/etc            CONF
/root           CONF
/boot           CONF

/var/log        LOGS

!/var/log/portage/    
!/var/tmp/            
!/tmp/                
!/var/cache/          
!/run/                
!/proc/               
!/sys/                
!/dev/                
