#==============================#
#                      _       #
#     ____ ___  ____ _(_)___   #
#    / __ `__ \/ __ `/ / __ \  #
#   / / / / / / /_/ / / / / /  #
#  /_/ /_/ /_/\__,_/_/_/ /_/   #
#                              #
#==============================#

# INFO: Sources all external configs and execs necessary tools

#---------------tells dbus about the current desktop
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
# openrc will ignore systemd flag. command will still work
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

#---------------kills all existing desktop portals; starts hyprlands
exec-once = ~/.config/hypr/xdg-portal-hyprland

#---------------starts polkit agent
exec-once = /usr/libexec/hyprpolkitagent

#---------------starts pipewire
exec-once = /usr/bin/gentoo-pipewire-launcher restart &

#---------------starts hyprpaper
exec-once = hyprpaper

#---------------starts hypridle
exec-once = hypridle

#---------------source configs
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/apps.conf
source = ~/.config/hypr/conf/inputs.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/themes/current.conf
