windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# KITTY FLOAT
windowrule = float, class:kitty
windowrule = size 700 450, class:kitty
windowrule = opacity 0.75, class:kitty

# FILE PICKER FLOAT
windowrule = float, title:^(Open Folder)$
windowrule = size 700 500, title:^(Open Folder)$

# OBSIDIAN OPACITY
windowrule = opacity 0.97, class:^(obsidian)$

# VSCODE
# windowrule = opacity 0.8, class:codium

# BLUEMAN
windowrule = float, class:^(blueman-manager)$
windowrule = size 500 700, class:^(blueman-manager)$

# ZATHURA OPACITY
windowrule = opacity 0.75, class:^(Zotero)$

# ZOTERO OPACITY
windowrule = opacity 0.85, class:^(Zotero)$