MAIL-ON-WARNING={{EMAIL}}
MAIL_CMD=mail -s "[rkhunter] Warnings found for ${HOST_NAME}"

DISABLE_TESTS=suspscan deleted_files

ALLOWHIDDENFILE=/etc/.java
ALLOWHIDDENDIR=/dev/.udev
ALLOWHIDDENDIR=/dev/.udevdb
ALLOWHIDDENDIR=/dev/.mdadm
